### ISSUE TITLE
Control signal is not clamped if the .ControlErrorIntegral becomes NaN

### ISSUE THREAD

**Issue by DmitryAndSoCs** [einride/pid-go#104]
I think I've found a bug with the package with AntiWindupController (I think it works for the others as well, didn't check)

If the control of the physical process fails (due to unrelated to the package reasons, ofc) and the feedback values are always giving the error (let's assume it stabilized at an offset from the setpoint), it would always accumulate `*.State.ControlErrorIntegral`. It's generally ok, but if the process is constantly offset, it accumulates error until it overflows and becomes NaN. In this case, the `*.State.ControlSignal` is not clamped as in normal operation. It may result in unexpected behaviour. 

In my case I just clamped the actual control signal additionally with checks (the approach)
```go 
if math.IsNaN(Controller.State.ControlSignal) || math.IsInf(Controller.State.ControlSignal) { // the last one is "just in case"
  actualSignal = Controller.Config.MaxOutput // or minimum
} else {
  actualSignal = Controller.State.ControlSignal
}
```

Not sure if it should be considered an issue, but I think it's worth mentioning.

**Comment by maxahlberg** [comment]
Hi @DmitryAndSoCs!

Thanks for your filed issue, what you are pointing out is completely right. 
We are [proposing](https://github.com/einride/pid-go/pull/108) a solution where we bound the `ControlErrorIntegral` which will prevent the `ControlSignal` from reaching NaN. We think that that would be a more expected behavior and then let the user set up a way to handle this thanks to having the visibility of the states of the controller. 

Happy to hear your feedback on the proposed solution.
